# -*- coding: utf-8 -*-
"""Gorkem_Kırdar.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_JteXYhxcfRujc4VqYyU7bHfzc_pecR2

*Hello*, please change the file name as your name_surname_MIDTERM.ipynb and upload to the folder 'DROP MIDTERMS HERE' on 
Drive.
ex: atay_ilgun_MIDTERM.ipynb

Also, create all TD related tasks on one TD file and upload it.
ex: atay_ilgun_MIDTERM.tox
"""

görkem kırdar

1235724

"""Describe what an algorithm is."""

In mathenatics and computer science, an algorithm is an clearly specification of how to solve a problems. Algorithms can perform calculation, data processing and automated reasoning task.

"""Explain in what ways algorithmic design is different than the brute-force regular design approach. [50 words]"""

Brute force method would systematically enumerates all the possible cases for the solution. It is generally the simplest and the most straightforward approach for the solution and will always find the solution if it exists but the cost could be high.As an example, suppose you have to find the sum of all natural numbers till n. Then the brute-force solution to find the sum would be to enumerate all numbers from 1 to n. But this is obviously not the cheapest solution.



"""In 100 words meditate on how an new approach on design such as one that is algorithmic could affect your work practice."""



"""Create a python dictionary for your name surname and year of birth."""

info = {'name':'görkem',
    'surname':'kırdar',
    'birth year':1994
       }
print(info['surname'])

"""Write a conditional so If the first letter of your name is 'a' print 'my initial is a!'"""

name = 'Görkem Kırdar'

name[0]

if name[0] == 'a|A':
  print ('my initial is an A')
  
else:
    print ('get the duck out of here')

"""Write a conditional so If your surnames letter count is divisable by 3 print 'it is divisible' if not 'not divisible'."""

surname = 'Kırdar'

if len(surname)%3 == 1:
  print('it is divisible')
  
else:
    print('what are you talking about')

"""Change your year of birth to 2678."""

info.update ({'birth year':'2678'})

print(info['birth year'])

"""TOUCHDESIGNER TIME.

Create a red box [in geo comp] and make it emit particles with a birth rate of 2500.
"""



"""Import a moving image and a sound file in TD.
Add at least two filters to the image file.
Make 2 parameters of these filters responsive to the audio.
"""



"""Create a torus and modify its x-size with an LFO with the frequency of 0.75."""



"""Create a sphere and create an amorph moving shape using 'noise'."""



"""Create a box and apply an image texture on it."""